/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package search;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static search.Search.frame;
import static search.Search.locmap;

/**
 *
 * @author User
 */
public class LocationDetails extends javax.swing.JPanel {

    /**
     * Creates new form LocationDetails
     * @param s
     * @param stringToAppend
     */
    public LocationDetails (String s,String stringToAppend) {
        initComponents();
        jLabel1.setText(locmapDetails.get(s));
        BufferedWriter bw = null;

      try {
         // APPEND MODE SET HERE
         bw = new BufferedWriter(new FileWriter("location.txt", true));
	 bw.write(stringToAppend);
	 bw.newLine();
	 bw.write(s);
         bw.newLine();
         bw.flush();
      } catch (IOException ioe) {
      } finally {                       // always close the file
	 if (bw != null) try {
	    bw.close();
	 } catch (IOException ioe2) {
	    // just ignore it
	 }
      } // end try/catch/finally

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();        jLabel2 = new javax.swing.JLabel();

        jLabel3 = new javax.swing.JLabel();        jLabel4 = new javax.swing.JLabel();


        setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search/Go-back-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search/Maps-Location-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
        );
        
        ImageIcon ic2= new javax.swing.ImageIcon(getClass().getResource("/home/1.jpg"));
        ic2.getImage().flush();

        jLabel4.setIcon(ic2); // NOI18N
        jLabel4.setText("");
        add(jLabel4);
        jLabel4.setBounds(250, 100, 600, 300);
       
        ImageIcon ic1 = new javax.swing.ImageIcon(getClass().getResource("/home/Signup.jpg"));
        ic1.getImage().flush();

        jLabel2.setIcon(ic1); // NOI18N
        jLabel2.setText("");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1100, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame.getContentPane().setVisible(false);
        searchhome temp=new searchhome();
        frame.setContentPane(temp);
        frame.getContentPane().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;    private javax.swing.JLabel jLabel4;

    // End of variables declaration//GEN-END:variables
    static Map<String, String> locmapDetails = new HashMap<String, String>();    
    static {
        FileReader fin = null;
        try {
            fin = new FileReader("locationDetails.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
        Scanner sc = new Scanner(fin);
        while (sc.hasNext()) {
            String input = sc.nextLine();
            String output = sc.nextLine();
            locmapDetails.put(input, output);
        }

    }
}
