/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Tanvir
 */
public class tplay extends javax.swing.JPanel {

    /**
     * Creates new form tplay
     */
    user player1, player2, player3, player4;
    static boolean semi1, semi2, fin;
    static user s1w, s2w, fw;

    public tplay() {
        initComponents();
    }

    public tplay(user player1, user player2, user player3, user player4) {
        initComponents();
        this.player1 = player1;
        this.player2 = player2;
        this.player3 = player3;
        this.player4 = player4;
        tplay.s1w = null;
        tplay.s2w = null;
        tplay.fw = null;
        tplay.semi1 = false;
        tplay.semi2 = false;
        tplay.fin = false;
        this.jLabel12.setText("Semifinal 1:" + player1.username + " vs " + player2.username);
        this.jLabel8.setText(player1.username);
        this.jLabel2.setText(player2.username);
        this.jLabel3.setText(player3.username);
        this.jLabel4.setText(player4.username);

    }

    public tplay(user player1, user player2, user player3, user player4, user player5) {
        initComponents();
        this.player1 = player1;
        this.player2 = player2;
        this.player3 = player3;
        this.player4 = player4;
        tplay.s1w = player5;
        tplay.s2w = null;
        tplay.fw = null;
        tplay.semi1 = true;
        tplay.semi2 = false;
        tplay.fin = false;
        this.jLabel12.setText("Semifinal 2:" + player3.username + " vs " + player4.username);
        this.jLabel8.setText(player1.username);
        this.jLabel2.setText(player2.username);
        this.jLabel3.setText(player3.username);
        this.jLabel4.setText(player4.username);
        this.jLabel1.setText(s1w.username);

    }

    public tplay(user player1, user player2, user player3, user player4, user player5, user player6) {
        initComponents();
        this.player1 = player1;
        this.player2 = player2;
        this.player3 = player3;
        this.player4 = player4;
        tplay.s1w = player5;
        tplay.s2w = player6;
        tplay.fw = null;
        tplay.semi1 = true;
        tplay.semi2 = true;
        tplay.fin = false;
        this.jLabel12.setText("Final:" + s1w.username + " vs " + s2w.username);
        this.jLabel8.setText(player1.username);
        this.jLabel2.setText(player2.username);
        this.jLabel3.setText(player3.username);
        this.jLabel4.setText(player4.username);
        this.jLabel1.setText(s1w.username);
        this.jLabel7.setText(s2w.username);

    }

    public tplay(user player1, user player2, user player3, user player4, user player5, user player6, user player7) {
        initComponents();
        this.player1 = player1;
        this.player2 = player2;
        this.player3 = player3;
        this.player4 = player4;
        tplay.s1w = player5;
        tplay.s2w = player6;
        tplay.fw = player7;
        tplay.semi1 = true;
        tplay.semi2 = true;
        tplay.fin = true;
        this.jLabel12.setText("End of tournament");
        this.jLabel8.setText(player1.username);
        this.jLabel2.setText(player2.username);
        this.jLabel3.setText(player3.username);
        this.jLabel4.setText(player4.username);
        this.jLabel1.setText(s1w.username);
        this.jLabel7.setText(s2w.username);
        this.jLabel10.setText("Winner: " + fw.username);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();        jLabel15 = new javax.swing.JLabel();


        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TBD");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("jLabel4");

        jLabel5.setText("Semifinal 1");

        jLabel6.setText("Semifinal 2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("TBD");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("jLabel1");

        jLabel9.setText("Final");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("TBD");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Play");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Tournament Home");
jLabel11.setForeground(Color.white);
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addComponent(jLabel11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                .addGap(50, 50, 50)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel9)
                                                                .addComponent(jLabel10)))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel7))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel4))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(362, Short.MAX_VALUE))
        );
        
        ImageIcon ic2 = new javax.swing.ImageIcon(getClass().getResource("/home/1.jpg"));
        ic2.getImage().flush();

        jLabel15.setIcon(ic2); // NOI18N
        jLabel15.setText("");
        add(jLabel15);
        jLabel15.setBounds(30, 50, 990, 450);
        ImageIcon ic = new javax.swing.ImageIcon(getClass().getResource("/home/Signup.jpg"));
        ic.getImage().flush();

        jLabel14.setIcon(ic); // NOI18N
        jLabel14.setText("");
        add(jLabel14);
        jLabel14.setBounds(0, 0, 1100, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Main.frame.setContentPane(new thome());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (player1.days > 0 && player2.days > 0 && player3.days > 0 && player4.days > 0) {
            if (fin) {
                System.out.println("complete");
            } else if (semi2) {
                System.out.println("play final");
                mygame.finl.us1 = player1;
                mygame.finl.us2 = player2;
                mygame.finl.us3 = player3;
                mygame.finl.us4 = player4;
                mygame.finl.us5 = s1w;
                mygame.finl.us6 = s2w;
                Thread t = new strtthrdfinl();
                t.start();
                this.setVisible(false);

            } else if (semi1) {
                System.out.println("play semi2");
                mygame.semi2.us1 = player1;
                mygame.semi2.us2 = player2;
                mygame.semi2.us3 = player3;
                mygame.semi2.us4 = player4;
                mygame.semi2.us5 = s1w;
                Thread t = new strtthrdsemi2();
                t.start();
                this.setVisible(false);
            } else {
                System.out.println("play semi1");
                mygame.semi1.us1 = player1;
                mygame.semi1.us2 = player2;
                mygame.semi1.us3 = player3;
                mygame.semi1.us4 = player4;

                Thread t = new strtthrdsemi1();
                t.start();
                this.setVisible(false);
            }
        } else {
            System.out.println("recharge");
            if (player1.days <= 0) {
                this.jLabel13.setText(player1.username + " needs to pay");
            } else if (player2.days <= 0) {
                this.jLabel13.setText(player2.username + " needs to pay");
            } else if (player3.days <= 0) {
                this.jLabel13.setText(player3.username + " needs to pay");
            } else if (player4.days <= 0) {
                this.jLabel13.setText(player4.username + " needs to pay");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;

    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
