/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tanvir
 */
public class userhome extends javax.swing.JPanel {

    /**
     * Creates new form userhome
     */
    public user us1, us2;

    void update() {
        this.userlb.setText(us1.name);
        this.jTextField1.setText("");
        this.daylb.setText(Integer.toString(us1.days));
        this.codelb.setText("");
        this.matchlb.setText(Integer.toString(us1.matches));
        this.wonlb.setText(Integer.toString(us1.won));
        this.lostlb.setText(Integer.toString(us1.lost));
        this.goallb.setText(Integer.toString(us1.goal));
        this.conlb.setText(Integer.toString(us1.conceded));
        int x = 0;
        if (us1.matches != 0) {
            x = (us1.won - us1.lost) * 100 / us1.matches;
        }
        this.perlb.setText(Integer.toString(x));

        this.userlb1.setText(us2.name);
        this.jTextField2.setText("");
        this.daylb1.setText(Integer.toString(us2.days));
        this.codelb1.setText("");
        this.matchlb1.setText(Integer.toString(us2.matches));
        this.wonlb1.setText(Integer.toString(us2.won));
        this.lostlb1.setText(Integer.toString(us2.lost));
        this.goallb1.setText(Integer.toString(us2.goal));
        this.conlb1.setText(Integer.toString(us2.conceded));
        x = 0;
        if (us2.matches != 0) {
            x = (us2.won - us2.lost) * 100 / us2.matches;
        }
        this.perlb1.setText(Integer.toString(x));

    }

    public userhome(user us1, user us2) {
        initComponents();
        this.us1 = us1;
        this.us2 = us2;

        update();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        userlb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        daylb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matchlb = new javax.swing.JLabel();
        wonlb = new javax.swing.JLabel();
        lostlb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        goallb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        conlb = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        perlb = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        codelb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        matchlb1 = new javax.swing.JLabel();
        wonlb1 = new javax.swing.JLabel();
        lostlb1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        goallb1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        conlb1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        perlb1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        userlb1 = new javax.swing.JLabel();
        codelb1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        daylb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        userlb.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        userlb.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Days remaining:");

        daylb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        daylb.setText("days");

        jLabel3.setText("Total matches:");

        jLabel4.setText("Won:");

        jLabel5.setText("Lost:");

        matchlb.setText("000");

        wonlb.setForeground(new java.awt.Color(0, 153, 0));
        wonlb.setText("000");

        lostlb.setForeground(new java.awt.Color(255, 0, 51));
        lostlb.setText("000");

        jLabel6.setText("Goals:");

        goallb.setForeground(new java.awt.Color(0, 204, 0));
        goallb.setText("000");

        jLabel8.setText("Conceded:");

        conlb.setForeground(new java.awt.Color(255, 51, 51));
        conlb.setText("000");

        jLabel10.setText("Win percentage:");

        perlb.setText("00");

        jButton2.setText("Enter passcode");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        codelb.setForeground(new java.awt.Color(204, 0, 0));

        jLabel7.setText("Total matches:");

        jLabel9.setText("Won:");

        jLabel11.setText("Lost:");

        matchlb1.setText("000");

        wonlb1.setForeground(new java.awt.Color(0, 153, 0));
        wonlb1.setText("000");

        lostlb1.setForeground(new java.awt.Color(255, 0, 51));
        lostlb1.setText("000");

        jLabel12.setText("Goals:");

        goallb1.setForeground(new java.awt.Color(0, 204, 0));
        goallb1.setText("000");

        jLabel13.setText("Conceded:");

        conlb1.setForeground(new java.awt.Color(255, 51, 51));
        conlb1.setText("000");

        jLabel14.setText("Win percentage:");

        perlb1.setText("00");

        jButton3.setText("Enter passcode");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        userlb1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        userlb1.setText("Username");

        codelb1.setForeground(new java.awt.Color(204, 0, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Days remaining:");

        daylb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        daylb1.setText("days");

        jButton1.setText("PLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(userlb, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(codelb, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(conlb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(goallb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(lostlb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(matchlb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(daylb))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(wonlb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(perlb))
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(codelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(wonlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(perlb1))
                                        .addComponent(userlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(matchlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(lostlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(goallb1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(conlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(daylb1)))
                                .addGap(102, 102, 102))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(userlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(daylb1))
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(matchlb1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(wonlb1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(lostlb1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(goallb1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel13)
                                                        .addComponent(conlb1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(perlb1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(userlb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(daylb))
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(matchlb))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(wonlb))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(lostlb))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(goallb))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(conlb))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(perlb))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(codelb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(codelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3)))
                                .addGap(27, 27, 27)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(551, Short.MAX_VALUE))
        );
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/1.jpg"))); // NOI18N
        jLabel17.setText("");
        add(jLabel17);
        jLabel17.setBounds(22, 35, 1050, 395);
        
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/signup.jpg"))); // NOI18N
        jLabel16.setText("");
        add(jLabel16);
        jLabel16.setBounds(0, 0, 1100, 900);

        
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        codedelclient cd = null;
        try {
            cd = new codedelclient(this.jTextField1.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(userhome.class.getName()).log(Level.SEVERE, null, ex);
        }
        int val = cd.val;
        if (val > 0) {
            this.us1.days += stgl.codemap.get(this.jTextField1.getText());
            stgl.codemap.remove(this.jTextField1.getText());
            update();
            this.codelb.setText("Done");
            //remove code from server
            //increase days in server
        } else {
            update();
            this.codelb.setText("Invalid or used code!");

        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        codedelclient cd = null;
        try {
            cd = new codedelclient(this.jTextField2.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(userhome.class.getName()).log(Level.SEVERE, null, ex);
        }
        int val = cd.val;
        if (val > 0) {
            this.us2.days += stgl.codemap.get(this.jTextField2.getText());
            stgl.codemap.remove(this.jTextField1.getText());
            update();
            this.codelb1.setText("Done");
            //remove code from server
            //increase days in server
        } else {
            update();
            this.codelb1.setText("Invalid or used code!");

        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        mygame.Main.us1 = us1;
        mygame.Main.us2 = us2;
        boolean b = true;
        if (us1.days <= 0) {
            this.codelb.setText("RECHARGE PLEASE");
        }
        if (us2.days <= 0) {
            this.codelb1.setText("RECHARGE PLEASE");
        }
        if (us1.days <= 0 || us2.days <= 0) {
            b = false;
        }
        if (b) {
            Thread t = new strtthrd();
            t.start();
            //this.setVisible(false);
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        Main.frame.setContentPane(new Signin());
    }

    // Variables declaration - do not modify                    
    private javax.swing.JLabel codelb;
    private javax.swing.JLabel codelb1;
    private javax.swing.JLabel conlb;
    private javax.swing.JLabel conlb1;
    private javax.swing.JLabel daylb;
    private javax.swing.JLabel daylb1;
    private javax.swing.JLabel goallb;
    private javax.swing.JLabel goallb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel17;

    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lostlb;
    private javax.swing.JLabel lostlb1;
    private javax.swing.JLabel matchlb;
    private javax.swing.JLabel matchlb1;
    private javax.swing.JLabel perlb;
    private javax.swing.JLabel perlb1;
    private javax.swing.JLabel userlb;
    private javax.swing.JLabel userlb1;
    private javax.swing.JLabel wonlb;
    private javax.swing.JLabel wonlb1;
    // End of variables declaration                  
}
